language: node_js
node_js:
    - "0.10"
    - "0.11"
    - "0.12"
services: 
    - mongodb
    - redis-server
before script:
    - npm install -g gulp    
script:
    - gulp build
    - npm run download-ip-country-db
    - npm run coveralls