language: node_js
node_js:
    - "0.10"
    - "0.11"
    - "0.12"
services: mongodb
before script:
    - npm install -g gulp    
script:
    - npm run download-ip-country-db
    - gulp build
    - npm run coveralls